### ISSUE TITLE
1.13.2-0.14.2 crashes on startup using 1.13.2-rift-1.0.4-SNAPSHOT

### ISSUE THREAD

**Issue by Luk2527** [maruohon/itemscroller#18]
[23:41:23] [main/INFO]: Loading tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[23:41:23] [main/INFO]: Using primary tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[23:41:23] [main/INFO]: Calling tweak class org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[23:41:23] [main/INFO]: Searching mods on classpath
[23:41:23] [main/INFO]: Loaded mod 'rift'
[23:41:23] [main/INFO]: Searching for mods in C:\mods
[23:41:23] [main/INFO]: Loaded mod 'itemscroller'
[23:41:23] [main/INFO]: Loaded mod 'voxelmap'
[23:41:23] [main/INFO]: Loaded 4 mods
[23:41:23] [main/INFO]: Initializing mods
[23:41:23] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:28) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-1.0.4-SNAPSHOT.jar:?]
	... 2 more
Caused by: java.lang.NoClassDefFoundError: fi/dy/masa/malilib/interfaces/IInitializationHandler
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:188) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:54) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-1.0.4-SNAPSHOT.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: fi.dy.masa.malilib.interfaces.IInitializationHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:188) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:54) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-1.0.4-SNAPSHOT.jar:?]
	... 2 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:188) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:54) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-1.0.4-SNAPSHOT.jar:?]
	... 2 more

**Comment by Luk2527** [comment]
Everything works fine without itemscroller-rift-1.13.2-0.14.2, but crashes when added. 
any suggestions???

**Comment by angrynerd** [comment]
Out of curiosity what version of java are you running and what other mods beside itemscroller and voxelmap are you running.

**Comment by maruohon** [comment]
You are missing the malilib library mod, which is required by the LiteLoader and Rift versions of Item Scroller.

**Comment by Luk2527** [comment]
> Out of curiosity what version of java are you running and what other mods beside itemscroller and voxelmap are you running.

Java version: 8.0.1910.12 x64
Mods : itemscorller, voxelmap and optifine

**Comment by Luk2527** [comment]
> You are missing the malilib library mod, which is required by the LiteLoader and Rift versions of Item Scroller.

Thank you @maruohon, added malilib and everything works fine now.
