### ISSUE TITLE
Incompatible mod versions - Item Scroller needs MaLiLib < 0.11 and does not like most recent releases

### ISSUE THREAD

**Issue by AvaNced-EJ25** [maruohon/itemscroller#75]
Item Scroller needs MaLiLib 0.10.0-dev.26 up to 0.11, but most recent version of MaLiLib is 0.11.6

This could be intended, but the version could also be misread on being checked. There has been multiple releases of MaLiLib past 0.11.0, so I am not sure if this is known and a new release of Itemscroller is being worked on, or if it is an unintended effect.

Not sure if this is an issue with Itemscroller or with MaLiLib

Below is the stack trace:

**Comment by AvaNced-EJ25** [comment]
`net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MaLiLib' (malilib) 0.11.6 (C:\Programs\MultiMC\instances\Fabric 1.18.1\.minecraft\mods\malilib-fabric-1.18.1-0.11.6.jar) with any version between 0.10.0-dev.26 (inclusive) and 0.11 (exclusive).
Unmet dependency listing:
	 - Mod 'Item Scroller' (itemscroller) 0.15.0 requires any version between 0.10.0-dev.26 (inclusive) and 0.11 (exclusive) of mod 'MaLiLib' (malilib), but only the wrong version is present: 0.11.6!
		 - Mod 'MaLiLib' (malilib) 0.11.6 is being loaded from C:\Programs\MultiMC\instances\Fabric 1.18.1\.minecraft\mods\malilib-fabric-1.18.1-0.11.6.jar
Inactive mods:
	 - mod 'MaLiLib' (malilib) 0.11.6, reason: to replace
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MaLiLib' (malilib) 0.11.6 (C:\Programs\MultiMC\instances\Fabric 1.18.1\.minecraft\mods\malilib-fabric-1.18.1-0.11.6.jar) with any version between 0.10.0-dev.26 (inclusive) and 0.11 (exclusive).
Unmet dependency listing:
	 - Mod 'Item Scroller' (itemscroller) 0.15.0 requires any version between 0.10.0-dev.26 (inclusive) and 0.11 (exclusive) of mod 'MaLiLib' (malilib), but only the wrong version is present: 0.11.6!
		 - Mod 'MaLiLib' (malilib) 0.11.6 is being loaded from C:\Programs\MultiMC\instances\Fabric 1.18.1\.minecraft\mods\malilib-fabric-1.18.1-0.11.6.jar
Inactive mods:
	 - mod 'MaLiLib' (malilib) 0.11.6, reason: to replace
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 11 more
`

**Comment by AvaNced-EJ25** [comment]
If instead version 0.10.0-dev.26 is used, it says it needs to be within 0.11.3 and 0.12

**Comment by maruohon** [comment]
I assume you have the older 1.18.0 version of Item Scroller then? Just get the 1.18.1 version, it's built for the new malilib and accepts that version.

**Comment by AvaNced-EJ25** [comment]
Yes I believe I am. I did not notice as they have the same version number. Version 0.15.0 for 1.18.1 works as expected.
