### ISSUE TITLE
Crash when Control + Left click vanilla crafting

### ISSUE THREAD

**Issue by MqcCheeze** [maruohon/itemscroller#99]
---- Minecraft Crash Report ----
// My bad.

Time: 2023-03-01 21:29:25
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7947()" because "newMouseStack" is null
	at net.minecraft.class_2813.handler$dbd005$onInit(class_2813.java:558)
	at net.minecraft.class_2813.<init>(class_2813.java:31)
	at net.minecraft.class_636.method_2906(class_636.java:465)
	at net.minecraft.class_465.method_2383(class_465.java:568)
	at net.minecraft.class_479.method_2383(class_479.java:109)
	at net.minecraft.class_465.method_25402(class_465.java:360)
	at net.minecraft.class_479.method_25402(class_479.java:98)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2813.handler$dbd005$onInit(class_2813.java:558)
	at net.minecraft.class_2813.<init>(class_2813.java:31)
	at net.minecraft.class_636.method_2906(class_636.java:465)
	at net.minecraft.class_465.method_2383(class_465.java:568)
	at net.minecraft.class_479.method_2383(class_479.java:109)
	at net.minecraft.class_465.method_25402(class_465.java:360)
	at net.minecraft.class_479.method_25402(class_479.java:98)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_479
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

-- Affected level --
Details:
	All players: 2 total; [class_746['MqcCheeze'/627821, l='ClientLevel', x=-298.75, y=63.00, z=31.60], class_745['spawn'/636581, l='ClientLevel', x=-292.66, y=63.00, z=40.29]]
	Chunk stats: 4096, 1543
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,67,0), Section: (at 0,3,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 6863523 game time, 3835750 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, file/Vanilla Tweaks, file/Unobtrusive, file/Quieter Sounds, itemswapper/default, armorchroma/alternative-icons, continuity/default, continuity/glass_pane_culling_fix, essential

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1461712896 bytes (1393 MiB) / 6182404096 bytes (5896 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2187
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29437.22
	Virtual memory used (MB): 18282.74
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 86.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		| Index | Mod                                               | ID                                            | Version                      |
		|------:|---------------------------------------------------|-----------------------------------------------|------------------------------|
		|   114 | Advanced XRay (Fabric)                            | advanced-xray-fabric                          | 1.19.3-1.3.0-build.14        |
		|    78 | Architectury                                      | architectury                                  | 7.0.66                       |
		|    29 | Armor Chroma                                      | armorchroma                                   | 1.2.4                        |
		|    72 | Better Biome Blend                                | betterbiomeblend                              | 1.19-1.3.6-fabric            |
		|    25 | Better Mount HUD                                  | bettermounthud                                | 1.2.1                        |
		|   130 | BetterF3                                          | betterf3                                      | 5.1.0                        |
		|     4 | Borderless Mining                                 | borderlessmining                              | 1.1.6+1.19.3                 |
		|     6 | CaffeineConfig                                    | caffeineconfig                                | 1.0.0+1.17                   |
		|   107 | Carpet Mod                                        | carpet                                        | 1.4.93                       |
		|    80 | Cloth Config v9                                   | cloth-config                                  | 9.0.94                       |
		|    27 | Continuity                                        | continuity                                    | 3.0.0-alpha.2+1.19.3         |
		|    21 | Dark Loading Screen                               | dark-loading-screen                           | 1.6.13                       |
		|    16 | Dynamic FPS                                       | dynamicfps                                    | 2.2.0                        |
		|    23 | EntityCulling-Fabric                              | entityculling                                 | 1.5.2-mc1.19.3               |
		|    65 | Error Notifier                                    | error_notifier                                | 1.0.9                        |
		|   127 | FerriteCore                                       | ferritecore                                   | 5.1.0                        |
		|    26 | Indium                                            | indium                                        | 1.0.12+mc1.19.3              |
		|    45 | Iris                                              | iris                                          | 1.5.1                        |
		|    28 | Item Scroller                                     | itemscroller                                  | 0.18.0                       |
		|    18 | ItemSwapper                                       | itemswapper                                   | 0.3.2-mc1.19.3               |
		|    36 | Java HotSpot(TM) 64-Bit Server VM                 | java                                          | 17                           |
		|   126 | Kirin UI                                          | kirin                                         | 1.13.2                       |
		|    10 | Krypton                                           | krypton                                       | 0.2.1                        |
		|    44 | LambDynamicLights                                 | lambdynlights                                 | 2.2.0+1.19.3                 |
		|    15 | LazyDFU                                           | lazydfu                                       | 0.1.3                        |
		|    71 | LibZoomer                                         | libzoomer                                     | 0.5.1+1.19.3                 |
		|     2 | Litematica                                        | litematica                                    | 0.13.1                       |
		|     8 | MaLiLib                                           | malilib                                       | 0.14.0                       |
		|   112 | Minecraft                                         | minecraft                                     | 1.19.3                       |
		|     5 | MiniHUD                                           | minihud                                       | 0.25.0                       |
		|     0 | MixinExtras                                       | com_github_llamalad7_mixinextras              | 0.1.1                        |
		|    57 | Mod Menu                                          | modmenu                                       | 5.0.2                        |
		|    54 | Ok Zoomer                                         | ok_zoomer                                     | 5.0.0-beta.10+1.19.3         |
		|   135 | Presence Footsteps                                | presencefootsteps                             | 1.7.1                        |
		|    50 | Pride Lib                                         | pride                                         | 1.2.0+1.19.3                 |
		|   133 | Quilt Advancement API                             | quilt_advancement                             | 4.0.0-beta.5+1.19.3          |
		|    66 | Quilt Base API                                    | quilt_base                                    | 4.0.0-beta.5+1.19.3          |
		|    84 | Quilt Biome API                                   | quilt_biome                                   | 4.0.0-beta.5+1.19.3          |
		|   129 | Quilt Block Content Registry API                  | quilt_block_content_registry                  | 4.0.0-beta.5+1.19.3          |
		|    58 | Quilt Block Entity API                            | quilt_block_entity                            | 4.0.0-beta.5+1.19.3          |
		|    41 | Quilt Block Extensions API                        | quilt_block_extensions                        | 4.0.0-beta.5+1.19.3          |
		|    83 | Quilt Client Command API                          | quilt_client_command                          | 4.0.0-beta.5+1.19.3          |
		|    40 | Quilt Command API                                 | quilt_command                                 | 4.0.0-beta.5+1.19.3          |
		|    81 | Quilt Crash Info                                  | quilt_crash_info                              | 4.0.0-beta.5+1.19.3          |
		|    52 | Quilt Dimension API                               | quilt_dimension                               | 4.0.0-beta.5+1.19.3          |
		|    67 | Quilt Entity API                                  | quilt_entity                                  | 4.0.0-beta.5+1.19.3          |
		|   113 | Quilt Entity Events                               | quilt_entity_events                           | 4.0.0-beta.5+1.19.3          |
		|    53 | Quilt Entity Networking API                       | quilt_entity_networking                       | 4.0.0-beta.5+1.19.3          |
		|    33 | Quilt Item Content Registry API                   | quilt_item_content_registry                   | 4.0.0-beta.5+1.19.3          |
		|    70 | Quilt Item Extension API                          | quilt_item_extension                          | 4.0.0-beta.5+1.19.3          |
		|    31 | Quilt Item Setting API                            | quilt_item_setting                            | 4.0.0-beta.5+1.19.3          |
		|   116 | Quilt Lifecycle Events                            | quilt_lifecycle_events                        | 4.0.0-beta.5+1.19.3          |
		|    85 | Quilt Loader                                      | quilt_loader                                  | 0.17.10                      |
		|    38 | Quilt Multipart Entity API                        | quilt_entity_multipart                        | 4.0.0-beta.5+1.19.3          |
		|    98 | Quilt Networking                                  | quilt_networking                              | 4.0.0-beta.5+1.19.3          |
		|    68 | Quilt Points of Interest                          | quilt_points_of_interest                      | 4.0.0-beta.5+1.19.3          |
		|   104 | Quilt Recipe API                                  | quilt_recipe                                  | 4.0.0-beta.5+1.19.3          |
		|    91 | Quilt Registry API                                | quilt_registry                                | 4.0.0-beta.5+1.19.3          |
		|    79 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment               | 4.0.0-beta.5+1.19.3          |
		|    95 | Quilt Resource Loader                             | quilt_resource_loader                         | 4.0.0-beta.5+1.19.3          |
		|    92 | Quilt Screen API                                  | quilt_screen                                  | 4.0.0-beta.5+1.19.3          |
		|   118 | Quilt Status Effect API                           | quilt_status_effect                           | 4.0.0-beta.5+1.19.3          |
		|   109 | Quilt Surface Rule API                            | quilt_surface_rule                            | 4.0.0-beta.5+1.19.3          |
		|    93 | Quilt Tags API                                    | quilt_tags                                    | 4.0.0-beta.5+1.19.3          |
		|   110 | Quilt Tooltip API                                 | quilt_tooltip                                 | 4.0.0-beta.5+1.19.3          |
		|    55 | Quilt Vehicle API                                 | quilt_vehicle                                 | 4.0.0-beta.5+1.19.3          |
		|    60 | Quilt Villager API                                | quilt_villager                                | 4.0.0-beta.5+1.19.3          |
		|    99 | Quilted Fabric API                                | quilted_fabric_api                            | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    77 | Quilted Fabric API Base                           | quilted_fabric_api_base                       | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    89 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1              | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    74 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                   | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   119 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                   | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   132 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1            | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   128 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1             | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    49 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    51 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    47 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    62 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   123 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0          | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    63 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1         | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    39 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1           | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    82 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1         | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   100 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    64 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1               | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   108 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0          | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    76 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0            | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    43 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1               | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    69 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    34 | Quilted Fabric Item Group API (v1)                | quilted_fabric_item_group_api_v1              | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   134 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1             | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   115 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    86 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1            | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   106 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    32 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    75 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   125 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1            | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    73 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                      | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    42 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    37 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1              | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    61 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1          | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   124 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                   | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   120 | Quilted Fabric Recipe API (v1)                    | quilted_fabric_recipe_api_v1                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   111 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0               | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    88 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    35 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    46 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1         | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    94 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                   | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    96 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                   | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    56 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1   | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    90 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1            | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    48 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1     | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   117 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0             | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   121 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   101 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1          | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|   103 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                   | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    97 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|    87 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1  | 5.0.0-alpha.9+0.72.0-1.19.3  |
		|     7 | Reese's Sodium Options                            | reeses-sodium-options                         | 1.4.9+mc1.19.2-build.67      |
		|    22 | Roughly Enough Items                              | roughlyenoughitems                            | 10.0.586                     |
		|    19 | Smooth Boot                                       | smoothboot                                    | 1.19-1.7.1                   |
		|   131 | Smooth Swapping                                   | smoothswapping                                | 0.6.1                        |
		|   105 | Sodium                                            | sodium                                        | 0.4.8+build.22               |
		|    59 | Sodium Extra                                      | sodium-extra                                  | 0.4.16+mc1.19.3-build.91     |
		|   122 | SpruceUI                                          | spruceui                                      | 4.1.0+1.19.3                 |
		|   102 | Starlight                                         | starlight                                     | 1.1.1+fabric.ae22326         |
		|     1 | Tweakeroo                                         | tweakeroo                                     | 0.15.0                       |
		|     9 | WorldEdit                                         | worldedit                                     | 7.2.13+46576cc               |
		|    12 | antlr4-runtime                                    | org_antlr_antlr4-runtime                      | 4.11.1                       |
		|    17 | cloth-basic-math                                  | cloth-basic-math                              | 0.6.1                        |
		|    13 | essential-container                               | essential-container                           | 1.0.0                        |
		|    30 | essential-loader                                  | essential-loader                              | 1.0.0                        |
		|    24 | glsl-transformer                                  | io_github_douira_glsl-transformer             | 2.0.0-pre8                   |
		|    14 | jcpp                                              | org_anarres_jcpp                              | 1.4.14                       |
		|    20 | occlusionculling                                  | com_logisticscraft_occlusionculling           | 0.0.6-SNAPSHOT               |
		|     3 | toml4j                                            | com_moandjiezana_toml_toml4j                  | 0.7.2                        |
		|    11 | velocity-native                                   | com_velocitypowered_velocity-native           | 3.1.2-SNAPSHOT               |
		|------:|---------------------------------------------------|-----------------------------------------------|------------------------------|
		
	Launched Version: quilt-loader-0.17.10-1.19.3
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.49, NVIDIA Corporation
	Window size: 1680x1050
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Vanilla Tweaks, file/Unobtrusive, file/Quieter Sounds, itemswapper/default, armorchroma/alternative-icons, continuity/default, continuity/glass_pane_culling_fix
	Current Language: English (United Kingdom)
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Server Running: true
	Player Count: 3 / 8; [EntityPlayerMPFake['End'/629274, l='ServerLevel[Survival Through The Updates S2]', x=-139.36, y=73.50, z=-1177.45], class_3222['MqcCheeze'/627821, l='ServerLevel[Survival Through The Updates S2]', x=-298.75, y=63.00, z=31.60], EntityPlayerMPFake['spawn'/636581, l='ServerLevel[Survival Through The Updates S2]', x=-292.66, y=63.00, z=40.29]]
	Data Packs: vanilla, file/afk display v1.1.3.zip, file/anti enderman grief v1.1.3.zip, file/crafting tweaks.zip, file/double shulker shells v1.3.3.zip, file/dragon drops v1.3.3.zip, file/larger phantoms v1.2.4.zip, file/more mob heads v2.11.0.zip, file/silence mobs v1.1.3.zip, file/spectator conduit power v1.1.3.zip, file/spectator night vision v1.1.3.zip, file/unlock all recipes v2.0.4.zip, file/wandering trades v1.6.0.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by MqcCheeze** [comment]
Happens when I try to craft 64 minecarts using vanilla control + left click

**Comment by MqcCheeze** [comment]
happens with bows aswell, I think its any non stackable are crafted, e.g. 64 bows when the inventory doesn't have that space avaliable
